services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    build: .
    depends_on:
      - redis
      - mongodb
    environment:
      - REDIS_URL=<your_redis_url>
      - MONGODB_URI=<your_mongodb_url>
      - NEWS_API_KEY=<your_newsAPI_key>
      - OPEN_WEATHER_API_KEY=<your_WeatherAPI_key>
      - SECRET_KEY=SECRET_KEY=<your_secret>
    ports:
      - "8000:80"
